apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-bridge-microservice
  namespace: cloud-connect
spec:
  selector:
    matchLabels:
      app: data-bridge-microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: data-bridge-microservice
    spec:
      containers:
      - name: data-bridge-microservice
        image: 209703339956.dkr.ecr.ap-southeast-1.amazonaws.com/data-bridge-microservice:1.0.28
        ports:
        - containerPort: 3000
        envFrom:
            - configMapRef:
                name: data-bridge-microservice-config
