apiVersion: v1
kind: Service
metadata:
  name: data-bridge-microservice
  namespace: cloud-connect
spec:
  selector:
    app: data-bridge-microservice
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort