apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-api-gateway
  namespace: cloud-connect
spec:
  selector:
    matchLabels:
      app: location-api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: location-api-gateway
    spec:
      containers:
      - name: location-api-gateway
        image: 209703339956.dkr.ecr.ap-southeast-1.amazonaws.com/location-api-gateway:1.0.41
        args: ["-NODE_ENV","development"]
        ports:
        - containerPort: 3000
        envFrom:
            - configMapRef:
                name: location-config
