apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-ms-api
  namespace: tracker
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        image: 922369738522.dkr.ecr.ap-southeast-2.amazonaws.com/tracker-microservice:1.0.52
        env:
        - name: DEPENV
          value: "PROD"
        - name: ENVIRONMENT
          value: "PROD"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-connection-string
  namespace: tracker
spec:
  data:
  - secretKey: connection-string
    remoteRef:
      key: "prd-eks-tracker-mongodb-connection-string"
      version: "AWSCURRENT"
