apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracker

resources:
- ../../base

patchesStrategicMerge:
- 6_tracker_ms_api.yaml
- 7_tracker_node_api.yaml
- 8_tracker_client.yaml
