apiVersion: v1
kind: Service
metadata:
  name: booking-api-gateway
  namespace: cloud-connect
spec:
  selector:
    app: booking-api-gateway
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort
