apiVersion: v1
kind: Service
metadata:
  name: sample-api-gateway
  namespace: cloud-connect
spec:
  selector:
    app: sample-api-gateway
  ports:
    - name: http
      port: 3010
      targetPort: 3010
  type: NodePort