apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: tracker
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.3.0
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        ports:
        - containerPort: 2181
          name: client
        # - containerPort: 2888
        #   name: peer
        # - containerPort: 3888
        #   name: leader-election
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper/data
        - name: zookeeper-logs
          mountPath: /var/lib/zookeeper/logs
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-csi
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: zookeeper-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-csi
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: tracker
spec:
  selector:
    app: zookeeper
  ports:
  - name: http
    port: 2181
  type: NodePort