apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: tracker
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      # initContainers:
      # - name: create-topic
      #   image: confluentinc/cp-kafka:7.3.0
      #   command: ['sh', '-c']
      #   args:
      #   - |
      #     echo "Waiting for Kafka to come online..."
      #     cub kafka-ready -b kafka-tracker.tracker.svc.cluster.local:9092 1 20 && \
      #     kafka-topics --create --if-not-exists --bootstrap-server kafka-tracker.tracker.svc.cluster.local:9092 --partitions 1 --replication-factor 1 --config cleanup.policy=compact --topic my_connect_offsets
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.3.0
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper.tracker.svc.cluster.local:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-tracker.tracker.svc.cluster.local:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: CONFLUENT_SUPPORT_CUSTOMER_ID
          value: "anonymous"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"

---
# The default service name, kafka, introduces conflicting env vars
# https://morioh.com/p/d1bafbd024d6
apiVersion: v1
kind: Service
metadata:
  name: kafka-tracker
  namespace: tracker
spec:
  selector:
    app: kafka
  ports:
    - name: http
      port: 9092
  type: NodePort