apiVersion: v1
kind: Service
metadata:
  name: cloudql-service
  namespace: cloud-connect
spec:
  selector:
    app: cloudql-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort
