apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-microservice
  namespace: cloud-connect
spec:
  selector:
    matchLabels:
      app: person-microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: person-microservice
    spec:
      containers:
      - name: person-microservice
        image: 209703339956.dkr.ecr.ap-southeast-1.amazonaws.com/person-microservice:1.0.36
        ports:
        - containerPort: 3000
        envFrom:
            - configMapRef:
                name: person-microservice-config
