apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-connect

resources:
- ../base
- configmap.yaml

patches:
- path: ingress.yaml
  target:
    kind: Ingress
    name: person-api-gateway
    namespace: cloud-connect