apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: cloud-connect
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  type: NodePort
  