apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: opusxenta
spec:
  selector:
    app: microservice
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort