apiVersion: v1
kind: Service
metadata:
  name: location-microservice
  namespace: cloud-connect
spec:
  selector:
    app: location-microservice
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort
