apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-client
  namespace: tracker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          image: 209703339956.dkr.ecr.ap-southeast-1.amazonaws.com/tracker-client:1.1.1
          env:
          - name: VERSION
            value: "1.1.1"
          - name: ENVIRONMENT
            value: "DEV"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysqldb-connection-string
  namespace: tracker
spec:
  dataFrom:
  - extract:
      key: "dev-eks-tracker-mysqldb-connection-string"
      version: AWSCURRENT
