apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: cloud-connect
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki-gateway:80/api/v1/push
    scrape_configs:
    - job_name: kubernetes-pods-name
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_name]
        target_label: __service__
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: __host__
      - action: keep
        source_labels: [__meta_kubernetes_pod_label_app]
        regex: person-api-gateway
          - action: replace
            source_labels:
        - __meta_kubernetes_pod_name
        - __meta_kubernetes_pod_label_name
        - __meta_kubernetes_pod_field_selector
        - __meta_kubernetes_pod_node_name
        - __meta_kubernetes_pod_label_app_kubernetes_io_instance
        - __meta_kubernetes_pod_label_app_kubernetes_io_name
        - __meta_kubernetes_pod_label_app_kubernetes_io_version
        - __meta_kubernetes_pod_label_app
        - __meta_kubernetes_pod_label_pod_template_hash
        - __meta_kubernetes_pod_label_controller_revision_hash
        target_label: instance
        replacement: $1
