apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: cloud-connect
spec:
  type: ClusterIP
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
    name: http
  selector:
    name: promtail
