apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: cloud-connect
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        envFrom:
            - configMapRef:
                name: zookeeper-config
